# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywl3MRYQ5UumiZ94v2_J3Rq9m2miUuOD
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

data=pd.read_excel("Data_Train.xlsx")
data.head()

data['Rating']=pd.to_numeric(data['Rating'].apply(lambda x: np.nan if x in ['Temporarily Closed','Opening Soon','-','NEW'] else x))
data['Votes']=pd.to_numeric(data['Votes'].apply(lambda x: np.nan if x=='-' else x))
data['Reviews']=pd.to_numeric(data['Reviews'].apply(lambda x: np.nan if x=='-' else x))

data['Rating']=data['Rating'].fillna(data['Rating'].median())
data['Votes']=data['Votes'].fillna(data['Votes'].median())
data['Reviews']=data['Reviews'].fillna(data['Reviews'].median())

transactions = []
for i in range(0, 7501):
    transactions.append([str(data.values[i,j]) for j in range(0, 9)])

from apyori import apriori
rules = apriori(transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2)

results = list(rules)

results

